name: storysaver
description: What's app story saver demo

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.1+2

environment:
  sdk: ">=2.14.0 <3.25.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  firebase_core: ^3.11.0
  firebase_analytics: ^11.4.2

  shared_preferences: ^2.1.0
  uuid: ^3.0.7
  app_tracking_transparency: ^2.0.2
  device_info_plus: ^11.3.0

  path_provider: ^2.0.11
  permission_handler: ^11.3.1
  # image_gallery_saver: ^1.7.1
#  image_gallery_saver: ^2.0.3
  video_player: ^2.4.7
  provider: ^6.0.3
  chewie: 1.8.0
  share_plus: 10.1.3
  url_launcher: ^6.3.1
  in_app_review: ^2.0.10

  pull_to_refresh_flutter3: ^2.0.2
  flutter_cache_manager: ^3.3.0
  photo_view: ^0.15.0

  photo_manager: ^3.6.4

  external_path: ^2.1.0

  smooth_page_indicator: ^1.2.0+3
  visibility_detector: ^0.4.0+2
  double_tap_to_exit: ^1.0.2

  video_compress: ^3.1.3
  list_all_videos: ^1.2.0
  flutter_isolate: ^2.1.0
  loader_overlay: ^5.0.0
  flutter_spinkit: ^5.2.1
  #  saf: ^1.0.3+4
#  file_picker: ^10.1.1
#  fluttertoast: ^8.2.12


  #  flutter_dotenv: ^5.2.1
  media_store_plus: ^0.1.3
#  video_compress_v2: ^1.0.0+1
  # image_picker: ^1.1.2
  # file_selector: ^1.0.3

  # video_thumbnail: ^0.5.3
#  get_thumbnail_video: ^0.7.2

#  flutter_video_thumbnail_plus: ^1.0.5

# list_all_videos: ^1.2.0
  # list_all_videos: ^1.0.9

dependency_overrides:
  device_info_plus: ^11.3.0
#  image_gallery_saver:
#    git:
#      url: https://github.com/knottx/image_gallery_saver.git
#      ref: knottx-latest

  media_scanner:
    git:
      url: https://github.com/mbfakourii/media_scanner.git
      ref: support_gradle_8

  saf:
    git:
      url: https://github.com/javed00700/saf.git


dev_dependencies:
  change_app_package_name: ^1.4.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.14.3"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/app_icon/status_saver.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/app-logo.png

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
#  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
#   assets:
#     - images/app-logo.png
#     - images/a_dot_ham.jpeg

#   uses-material-design: true

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
